# Generated by Django 2.2.6 on 2019-10-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=16)),
                ('currency', models.CharField(choices=[('USD', 'Dollar'), ('EUR', 'EURO'), ('HKD', 'Hongkong Dollar'), ('JYP', 'Japanese Yen')], default='USD', max_length=16)),
                ('exchange', models.CharField(choices=[('CME', 'CME'), ('NYMEX', 'NYMEX'), ('CBOE', 'CBOE'), ('CBOT', 'CBOT'), ('EUREX', 'EUREX'), ('HKEX', 'HKEX'), ('SGX', 'SGX'), ('ICE_US', 'ICE_US')], max_length=16)),
                ('market', models.CharField(choices=[('CUR', '통화'), ('IDX', '지수'), ('INT', '금리'), ('ENG', '에너지'), ('MTL', '금속'), ('Grain', '곡물'), ('Tropical', '열대과일'), ('Meat', '육류')], max_length=16)),
                ('tickunit', models.FloatField()),
                ('tickprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('margin', models.PositiveIntegerField()),
                ('opentime', models.TimeField()),
                ('closetime', models.TimeField()),
                ('decimal_length', models.SmallIntegerField()),
            ],
        ),
    ]
