# Generated by Django 2.2.6 on 2019-10-30 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuturesEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='진입 날짜')),
                ('position', models.SmallIntegerField(choices=[(1, 'Long'), (-1, 'Short')], verbose_name='포지션')),
                ('quantity', models.SmallIntegerField(verbose_name='계약수')),
                ('price', models.FloatField(verbose_name='진입가')),
                ('riskprice', models.FloatField(verbose_name='손절가')),
                ('stopprice', models.FloatField(verbose_name='청산 예정가')),
                ('commission', models.FloatField(default=0, verbose_name='수수료')),
                ('cum_commission', models.FloatField(default=0, verbose_name='누적수수료')),
                ('entryrisk', models.FloatField(blank=True, verbose_name='진입 리스크')),
                ('is_open', models.BooleanField(default=True, verbose_name='매매 상태')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='FuturesSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opendate', models.DateField(verbose_name='운용 시작일')),
                ('name', models.CharField(max_length=64, verbose_name='시스템명')),
                ('symbol', models.CharField(max_length=16, verbose_name='시스템코드')),
                ('principal', models.PositiveIntegerField(verbose_name='투자원금(KRW)')),
                ('count', models.PositiveIntegerField(blank=True, null=True, verbose_name='매매횟수')),
                ('gross_return', models.FloatField(default=0, verbose_name='누적손익')),
                ('gross_return_ratio', models.FloatField(default=0, verbose_name='누적수익률')),
                ('average_ptr', models.FloatField(default=0, verbose_name='평균손익비')),
                ('winning_rate', models.FloatField(default=0, verbose_name='승률')),
                ('average_profit', models.FloatField(default=0, verbose_name='평균수익')),
                ('std', models.FloatField(default=0, verbose_name='수익표준편차')),
                ('dd', models.FloatField(default=0, verbose_name='자본인하율')),
                ('mdd', models.FloatField(default=0, verbose_name='최대자본인하율')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='평균보유기간')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='상품명')),
                ('symbol', models.CharField(max_length=16, verbose_name='상품코드')),
                ('currency', models.CharField(choices=[('USD', 'Dollar'), ('EUR', 'EURO'), ('HKD', 'Hongkong Dollar'), ('JYP', 'Japanese Yen')], default='USD', max_length=16, verbose_name='거래 통화')),
                ('exchange', models.CharField(choices=[('CME', 'CME'), ('NYMEX', 'NYMEX'), ('CBOE', 'CBOE'), ('CBOT', 'CBOT'), ('EUREX', 'EUREX'), ('HKEX', 'HKEX'), ('SGX', 'SGX'), ('ICE_US', 'ICE_US')], max_length=16, verbose_name='거래소')),
                ('market', models.CharField(choices=[('CUR', '통화'), ('IDX', '지수'), ('INT', '금리'), ('ENG', '에너지'), ('MTL', '금속'), ('Grain', '곡물'), ('Tropical', '열대과일'), ('Meat', '육류')], max_length=16, verbose_name='시장 구분')),
                ('tickunit', models.FloatField(verbose_name='호가 단위')),
                ('tickprice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='호가당 가격')),
                ('margin', models.PositiveIntegerField(verbose_name='증거금')),
                ('opentime', models.TimeField(verbose_name='거래 시작시간')),
                ('closetime', models.TimeField(verbose_name='거래 종료시간')),
                ('decimal_length', models.SmallIntegerField(verbose_name='소수점 자리수')),
            ],
        ),
        migrations.CreateModel(
            name='FuturesExit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='청산날짜')),
                ('quantity', models.SmallIntegerField(verbose_name='계약수')),
                ('price', models.FloatField(verbose_name='청산가격')),
                ('profit', models.FloatField(blank=True, verbose_name='손익')),
                ('cum_profit', models.FloatField(blank=True, verbose_name='누적손익')),
                ('ptr', models.FloatField(blank=True, verbose_name='손익비')),
                ('duration', models.DurationField(blank=True, verbose_name='보유기간')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exits', to='trading.FuturesEntry', verbose_name='진입매매')),
            ],
        ),
        migrations.AddField(
            model_name='futuresentry',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading.Instrument', verbose_name='상품명'),
        ),
        migrations.AddField(
            model_name='futuresentry',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='trading.FuturesSystem', verbose_name='시스템'),
        ),
    ]
