# Generated by Django 2.2.6 on 2019-11-03 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuturesEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='진입 날짜')),
                ('position', models.SmallIntegerField(choices=[(1, 'Long'), (-1, 'Short')], verbose_name='포지션')),
                ('quantity', models.SmallIntegerField(verbose_name='계약수')),
                ('price', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='진입가')),
                ('riskprice', models.DecimalField(blank=True, decimal_places=6, max_digits=12, verbose_name='손절가')),
                ('stopprice', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='청산 예정가')),
                ('open_cons', models.SmallIntegerField(verbose_name='미청산계약수')),
                ('close_cons', models.SmallIntegerField(default=0, verbose_name='청산계약수')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='수수료')),
                ('commission_krw', models.DecimalField(blank=True, decimal_places=0, max_digits=9, verbose_name='수수료(원)')),
                ('entry_risk', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='진입 리스크')),
                ('current_risk', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='현재 리스크')),
                ('is_open', models.BooleanField(default=True, verbose_name='상태')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='FuturesExit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='청산날짜')),
                ('quantity', models.SmallIntegerField(verbose_name='계약수')),
                ('price', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='청산가격')),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='손익')),
                ('profit_krw', models.DecimalField(blank=True, decimal_places=0, max_digits=10, verbose_name='손익(원)')),
                ('duration', models.DurationField(blank=True, verbose_name='보유기간')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exits', to='trading.FuturesEntry', verbose_name='진입매매')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='FuturesSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opendate', models.DateField(verbose_name='운용 시작일')),
                ('name', models.CharField(max_length=64, verbose_name='시스템명')),
                ('symbol', models.CharField(max_length=16, verbose_name='시스템코드')),
                ('principal_krw', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='투자원금(KRW)')),
                ('principal_usd', models.DecimalField(blank=True, decimal_places=0, max_digits=6, verbose_name='투자원금(USD)')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='상품명')),
                ('symbol', models.CharField(max_length=16, verbose_name='상품코드')),
                ('currency', models.CharField(choices=[('USD', 'Dollar'), ('EUR', 'EURO'), ('HKD', 'Hongkong Dollar'), ('JYP', 'Japanese Yen')], default='USD', max_length=16, verbose_name='거래 통화')),
                ('exchange', models.CharField(choices=[('CME', 'CME'), ('NYMEX', 'NYMEX'), ('CBOE', 'CBOE'), ('CBOT', 'CBOT'), ('EUREX', 'EUREX'), ('HKEX', 'HKEX'), ('SGX', 'SGX'), ('ICE_US', 'ICE_US')], max_length=16, verbose_name='거래소')),
                ('market', models.CharField(choices=[('CUR', '통화'), ('IDX', '지수'), ('INT', '금리'), ('ENG', '에너지'), ('MTL', '금속'), ('Grain', '곡물'), ('Tropical', '열대과일'), ('Meat', '육류')], max_length=16, verbose_name='시장 구분')),
                ('tickunit', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='호가 단위')),
                ('tickprice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='호가당 가격')),
                ('margin', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='증거금')),
                ('decimal_places', models.SmallIntegerField(verbose_name='소수점 자리수')),
                ('current_price', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='현재가')),
                ('opentime', models.TimeField(verbose_name='거래 시작시간')),
                ('closetime', models.TimeField(verbose_name='거래 종료시간')),
            ],
        ),
        migrations.CreateModel(
            name='StockStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='매매시작일')),
                ('name', models.CharField(max_length=50, verbose_name='종목명')),
                ('code', models.CharField(max_length=10, verbose_name='종목코드')),
                ('current_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='현재가')),
                ('stop_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='청산예정가')),
                ('purchase_money', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='총매입금')),
                ('buy_quantity', models.PositiveIntegerField(default=0, verbose_name='총매입주식수')),
                ('sell_quantity', models.PositiveIntegerField(default=0, verbose_name='총청산주식수')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='보유주식수')),
                ('average_purchase_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='평균매수단가')),
                ('average_sell_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='평균매도단가')),
                ('stock_value', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='주식가치')),
                ('liquidation', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='총청산금')),
                ('dividends', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='배당금')),
                ('is_open', models.BooleanField(default=True, verbose_name='매매상태')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='StockSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='날짜')),
                ('principal', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='투자원금')),
                ('cash', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='보유현금')),
                ('stock', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='주식가치')),
                ('profit', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='누적수익')),
                ('rate_of_return', models.FloatField(default=0, verbose_name='수익률')),
            ],
        ),
        migrations.CreateModel(
            name='StockSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='청산일')),
                ('quantity', models.PositiveIntegerField(verbose_name='청산수량')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='청산가격')),
                ('liquidation', models.DecimalField(blank=True, decimal_places=0, max_digits=10, verbose_name='청산금액')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sells', to='trading.StockStatement', verbose_name='매매')),
            ],
        ),
        migrations.CreateModel(
            name='StockBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='진입일')),
                ('quantity', models.PositiveIntegerField(verbose_name='매수수량')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='매수가격')),
                ('purchase_money', models.DecimalField(blank=True, decimal_places=0, max_digits=10, verbose_name='매입금액')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buys', to='trading.StockStatement', verbose_name='매매')),
            ],
        ),
        migrations.CreateModel(
            name='FuturesTrackRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='날짜')),
                ('count', models.PositiveIntegerField(verbose_name='매매횟수')),
                ('gross_return', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='누적손익(달러)')),
                ('gross_return_krw', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='누적손익(원)')),
                ('gross_return_ratio', models.FloatField(verbose_name='누적수익률')),
                ('average_ptr', models.FloatField(verbose_name='평균손익비')),
                ('winning_rate', models.FloatField(verbose_name='승률')),
                ('average_profit', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='평균수익')),
                ('average_profit_krw', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='평균수익(원)')),
                ('std', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='수익표준편차')),
                ('std_krw', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='수익표준편차(원)')),
                ('dd', models.FloatField(verbose_name='자본인하율')),
                ('mdd', models.FloatField(verbose_name='최대자본인하율')),
                ('duration', models.PositiveIntegerField(verbose_name='평균보유기간')),
                ('risk_per_trade', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='매매당리스크')),
                ('risk', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='현재총리스크')),
                ('risk_per_trade_krw', models.DecimalField(blank=True, decimal_places=0, max_digits=9, verbose_name='매매당리스크(원)')),
                ('risk_krw', models.DecimalField(blank=True, decimal_places=0, max_digits=9, verbose_name='현재총리스크(원)')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='누적수수료')),
                ('commission_krw', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='누적수수료(원)')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.FuturesEntry')),
                ('exit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.FuturesExit')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='trading.FuturesSystem', verbose_name='시스템실적')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AddField(
            model_name='futuresentry',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading.Instrument', verbose_name='상품명'),
        ),
        migrations.AddField(
            model_name='futuresentry',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='trading.FuturesSystem', verbose_name='시스템'),
        ),
    ]
