# Generated by Django 2.2.6 on 2019-10-30 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futuressystem',
            name='duration',
        ),
    ]
