# Generated by Django 2.2.6 on 2019-11-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuressystem',
            name='principal_usd',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='투자원금(USD)'),
        ),
        migrations.AlterField(
            model_name='futuressystem',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='매매횟수'),
        ),
    ]
