# Generated by Django 2.2.6 on 2019-11-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashaccount',
            name='date',
            field=models.DateField(verbose_name='날짜'),
        ),
        migrations.AlterField(
            model_name='cashaccount',
            name='symbol',
            field=models.CharField(default='C', max_length=16, verbose_name='계좌코드'),
        ),
        migrations.AlterField(
            model_name='futuresentry',
            name='current_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='평가손익'),
        ),
        migrations.AlterField(
            model_name='futuresentry',
            name='current_risk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='현재 리스크'),
        ),
        migrations.AlterField(
            model_name='futuresentry',
            name='entry_risk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='진입 리스크'),
        ),
        migrations.AlterField(
            model_name='stockaccount',
            name='date',
            field=models.DateField(verbose_name='날짜'),
        ),
        migrations.AlterField(
            model_name='stockaccount',
            name='symbol',
            field=models.CharField(default='S', max_length=16, verbose_name='계좌코드'),
        ),
    ]
