# Generated by Django 2.2.6 on 2019-10-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_remove_futuressystem_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuressystem',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='평균보유기간'),
        ),
    ]
