# Generated by Django 2.2.6 on 2019-11-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_auto_20191109_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktradeunit',
            name='avg_buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='평균매수단가'),
        ),
        migrations.AlterField(
            model_name='stocktradeunit',
            name='avg_sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='평균매도단가'),
        ),
    ]
