# Generated by Django 2.2.6 on 2019-11-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_auto_20191101_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='decimal_length',
            new_name='decimal_places',
        ),
        migrations.AlterField(
            model_name='futuresentry',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='수수료'),
        ),
        migrations.AlterField(
            model_name='futuresentry',
            name='commission_krw',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, verbose_name='수수료(원)'),
        ),
        migrations.AlterField(
            model_name='futuresentry',
            name='cum_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='수수료'),
        ),
        migrations.AlterField(
            model_name='futuresentry',
            name='cum_commission_krw',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, verbose_name='수수료'),
        ),
        migrations.AlterField(
            model_name='futuresentry',
            name='entryrisk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='진입 리스크'),
        ),
        migrations.AlterField(
            model_name='futuresentry',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='진입가'),
        ),
        migrations.AlterField(
            model_name='futuresentry',
            name='riskprice',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='손절가'),
        ),
        migrations.AlterField(
            model_name='futuresentry',
            name='stopprice',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='청산 예정가'),
        ),
        migrations.AlterField(
            model_name='futuresexit',
            name='cum_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='누적손익'),
        ),
        migrations.AlterField(
            model_name='futuresexit',
            name='cum_profit_krw',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, verbose_name='누적손익(원))'),
        ),
        migrations.AlterField(
            model_name='futuresexit',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=6, verbose_name='청산가격'),
        ),
        migrations.AlterField(
            model_name='futuresexit',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='손익'),
        ),
        migrations.AlterField(
            model_name='futuresexit',
            name='profit_krw',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, verbose_name='손익(원)'),
        ),
        migrations.AlterField(
            model_name='futuressystem',
            name='average_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='평균수익'),
        ),
        migrations.AlterField(
            model_name='futuressystem',
            name='average_profit_krw',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='평균수익(원)'),
        ),
        migrations.AlterField(
            model_name='futuressystem',
            name='gross_return',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='누적손익(달러)'),
        ),
        migrations.AlterField(
            model_name='futuressystem',
            name='gross_return_krw',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='누적손익(원)'),
        ),
        migrations.AlterField(
            model_name='futuressystem',
            name='principal',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='투자원금(KRW)'),
        ),
        migrations.AlterField(
            model_name='futuressystem',
            name='principal_usd',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, verbose_name='투자원금(USD)'),
        ),
        migrations.AlterField(
            model_name='futuressystem',
            name='std',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='수익표준편차'),
        ),
        migrations.AlterField(
            model_name='futuressystem',
            name='std_krw',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='수익표준편차(원)'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='margin',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='증거금'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='tickunit',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='호가 단위'),
        ),
    ]
