# Generated by Django 2.2.6 on 2019-11-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_auto_20191101_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuresexit',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='청산가격'),
        ),
    ]
