# Generated by Django 2.2.6 on 2019-10-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_futuressystem_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuresentry',
            name='commission_krw',
            field=models.FloatField(default=0, verbose_name='수수료(원)'),
        ),
        migrations.AddField(
            model_name='futuresentry',
            name='cum_commission_krw',
            field=models.FloatField(default=0, verbose_name='누적수수료(원)'),
        ),
        migrations.AddField(
            model_name='futuresentry',
            name='timestamp',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='타임스탬프'),
        ),
        migrations.AddField(
            model_name='futuresexit',
            name='cum_profit_krw',
            field=models.FloatField(blank=True, null=True, verbose_name='누적손익(원)'),
        ),
        migrations.AddField(
            model_name='futuresexit',
            name='profit_krw',
            field=models.FloatField(blank=True, null=True, verbose_name='손익(원)'),
        ),
        migrations.AddField(
            model_name='futuresexit',
            name='timestamp',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='타임스탬프'),
        ),
        migrations.AddField(
            model_name='futuressystem',
            name='average_profit_krw',
            field=models.FloatField(default=0, verbose_name='평균수익(원)'),
        ),
        migrations.AddField(
            model_name='futuressystem',
            name='gross_return_krw',
            field=models.FloatField(default=0, verbose_name='누적손익(원)'),
        ),
        migrations.AddField(
            model_name='futuressystem',
            name='std_krw',
            field=models.FloatField(default=0, verbose_name='수익표준편차(원)'),
        ),
        migrations.AlterField(
            model_name='futuressystem',
            name='gross_return',
            field=models.FloatField(default=0, verbose_name='누적손익(달러)'),
        ),
    ]
