# Generated by Django 2.2.6 on 2019-12-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_auto_20191112_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('acc_from', models.CharField(choices=[('N', '없음'), ('C', '현금'), ('FM', '선물_1'), ('S', '주식')], max_length=10, verbose_name='출금계좌')),
                ('currency_from', models.CharField(choices=[('KRW', '원'), ('USD', '달러'), ('CNY', '위안')], max_length=10, verbose_name='출금통화')),
                ('amount_from', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='출금액')),
                ('acc_to', models.CharField(choices=[('N', '없음'), ('C', '현금'), ('FM', '선물_1'), ('S', '주식')], max_length=10, verbose_name='입금계좌')),
                ('currency_to', models.CharField(choices=[('KRW', '원'), ('USD', '달러'), ('CNY', '위안')], max_length=10, verbose_name='입금통화')),
                ('amount_to', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='입금액')),
            ],
        ),
    ]
