# Generated by Django 2.2.6 on 2019-11-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_auto_20191101_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='futuresentry',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='futuresexit',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='futuresentry',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='futuresexit',
            name='created_date',
        ),
    ]
