# Generated by Django 2.2.6 on 2019-11-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_auto_20191101_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futuresexit',
            name='ptr',
        ),
    ]
