# Generated by Django 2.2.6 on 2019-12-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_auto_20191206_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuresentry',
            name='expiration',
            field=models.DateField(null=True, verbose_name='만기일'),
        ),
    ]
