# Generated by Django 2.2.6 on 2019-10-31 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_auto_20191031_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuresexit',
            name='timestamp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='타임스탬프'),
        ),
    ]
