# Generated by Django 2.2.6 on 2020-02-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_futuresentry_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuresaccount',
            name='principal_eur',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='투자원금(EUR)'),
        ),
    ]
