# Generated by Django 2.2.6 on 2019-10-31 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_auto_20191031_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futuresentry',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='futuresexit',
            name='timestamp',
        ),
    ]
