# Generated by Django 2.2.6 on 2019-11-01 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_remove_futuresexit_ptr'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='매매시작일')),
                ('name', models.CharField(max_length=50, verbose_name='종목명')),
                ('current_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='현재가')),
                ('stop_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='청산예정가')),
                ('purchase_money', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='총매입금')),
                ('buy_quantity', models.PositiveIntegerField(default=0, verbose_name='총매입주식수')),
                ('sell_quantity', models.PositiveIntegerField(default=0, verbose_name='총청산주식수')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='보유주식수')),
                ('average_purchase_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='평균단가')),
                ('stock_value', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='주식가치')),
                ('liquidation', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='총청산금')),
                ('dividends', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='배당금')),
                ('is_open', models.BooleanField(default=True, verbose_name='매매상태')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='StockSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='날짜')),
                ('principal', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='투자원금')),
                ('cash', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='보유현금')),
                ('stock', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='주식가치')),
                ('profit', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='누적수익')),
                ('rate_of_return', models.FloatField(default=0, verbose_name='수익률')),
            ],
        ),
        migrations.CreateModel(
            name='StockSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='청산일')),
                ('quantity', models.PositiveIntegerField(verbose_name='청산수량')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='청산가격')),
                ('liquidation', models.DecimalField(blank=True, decimal_places=0, max_digits=10, verbose_name='청산금액')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sells', to='trading.StockStatement', verbose_name='매매')),
            ],
        ),
        migrations.CreateModel(
            name='StockBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='진입일')),
                ('quantity', models.PositiveIntegerField(verbose_name='매수수량')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='매수가격')),
                ('purchase_money', models.DecimalField(blank=True, decimal_places=0, max_digits=10, verbose_name='매입금액')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buys', to='trading.StockStatement', verbose_name='매매')),
            ],
        ),
    ]
