# Generated by Django 2.2.6 on 2020-02-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_futuresaccount_principal_eur'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuresinstrument',
            name='number_system',
            field=models.SmallIntegerField(choices=[(10, '십진법'), (8, '8진법'), (32, '32진법')], default=10, verbose_name='진법'),
        ),
    ]
