# Generated by Django 2.2.6 on 2019-11-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_stockbuy_stocksell_stockstatement_stocksummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockstatement',
            name='average_sell_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='평균매도단가'),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='average_purchase_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='평균매수단가'),
        ),
    ]
