# Generated by Django 2.2.6 on 2019-11-01 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_auto_20191101_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocksell',
            old_name='statement',
            new_name='trade',
        ),
    ]
