# Generated by Django 2.2.6 on 2020-02-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_futuresinstrument_number_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuresaccount',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, verbose_name='수수료'),
        ),
        migrations.AlterField(
            model_name='futuresinstrument',
            name='number_system',
            field=models.SmallIntegerField(choices=[(10, '10진법'), (8, '8진법'), (32, '32진법')], default=10, verbose_name='진법'),
        ),
    ]
