# Generated by Django 3.0.3 on 2020-03-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_auto_20200228_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futuresaccount',
            name='std',
        ),
        migrations.AddField(
            model_name='futuresaccount',
            name='value_eur',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='유로자산가치(EUR)'),
        ),
        migrations.AddField(
            model_name='futuresaccount',
            name='value_usd',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='달러자산가치(USD)'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='currency_from',
            field=models.CharField(blank=True, choices=[('KRW', '원'), ('USD', '달러'), ('CNY', '위안'), ('EUR', '유로')], max_length=10, null=True, verbose_name='출금통화'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='currency_to',
            field=models.CharField(choices=[('KRW', '원'), ('USD', '달러'), ('CNY', '위안'), ('EUR', '유로')], max_length=10, verbose_name='입금통화'),
        ),
    ]
