# Generated by Django 3.0.3 on 2020-03-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_auto_20200305_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuresexit',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='수수료'),
        ),
    ]
