# Generated by Django 4.1.1 on 2022-09-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_auto_20201005_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='acc_from',
            field=models.CharField(choices=[('N', '없음'), ('C', '현금'), ('S', '주식'), ('FM01', '선물(해선추세)'), ('FM02', '선물(해선단타)')], max_length=10, verbose_name='출금계좌'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='acc_to',
            field=models.CharField(choices=[('N', '없음'), ('C', '현금'), ('S', '주식'), ('FM01', '선물(해선추세)'), ('FM02', '선물(해선단타)')], max_length=10, verbose_name='입금계좌'),
        ),
    ]
