# Generated by Django 4.1.1 on 2022-12-01 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0019_alter_transfer_acc_from_alter_transfer_acc_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturesStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='전략명')),
                ('code', models.CharField(max_length=10, verbose_name='전략코드')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
            ],
        ),
        migrations.AlterField(
            model_name='transfer',
            name='acc_from',
            field=models.CharField(choices=[('N', '없음'), ('C', '현금'), ('S', '주식'), ('FM', '선물(자유매매)'), ('FM02', '선물(해선단타)')], max_length=10, verbose_name='출금계좌'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='acc_to',
            field=models.CharField(choices=[('N', '없음'), ('C', '현금'), ('S', '주식'), ('FM', '선물(자유매매)'), ('FM02', '선물(해선단타)')], max_length=10, verbose_name='입금계좌'),
        ),
        migrations.AddField(
            model_name='futuresentry',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='trading.futuresstrategy', verbose_name='전략'),
        ),
    ]
