# Generated by Django 4.1.3 on 2022-12-10 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0020_futuresstrategy_alter_transfer_acc_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuresinstrument',
            name='ebest_symbol',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='이베스트 상품코드'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='acc_from',
            field=models.CharField(choices=[('N', '없음'), ('C', '현금'), ('S', '주식'), ('FM01', '선물(해선추세)'), ('FM02', '선물(해선단타)')], max_length=10, verbose_name='출금계좌'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='acc_to',
            field=models.CharField(choices=[('N', '없음'), ('C', '현금'), ('S', '주식'), ('FM01', '선물(해선추세)'), ('FM02', '선물(해선단타)')], max_length=10, verbose_name='입금계좌'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebest_id', models.PositiveSmallIntegerField(verbose_name='이베스트 체결번호')),
                ('ebest_code', models.CharField(max_length=20, verbose_name='이베스트 상품코드')),
                ('date', models.DateTimeField(verbose_name='체결날짜')),
                ('position', models.SmallIntegerField(choices=[(1, 'Long'), (-1, 'Short')], verbose_name='포지션')),
                ('num_cons', models.SmallIntegerField(verbose_name='진입계약수')),
                ('entry_price', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='진입가')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='수수료')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading.futuresinstrument', verbose_name='상품')),
            ],
        ),
    ]
