# Generated by Django 4.1.3 on 2022-12-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0022_remove_futuresinstrument_ebest_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ebest_id',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='이베스트 체결번호'),
        ),
    ]
