# Generated by Django 4.1.3 on 2022-12-12 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0023_alter_transaction_ebest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_entry',
            field=models.BooleanField(default=True, verbose_name='매매종류'),
        ),
        migrations.CreateModel(
            name='FuturesTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='시작날짜')),
                ('ebest_code', models.CharField(max_length=20, verbose_name='이베스트 상품코드')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading.futuresinstrument', verbose_name='상품')),
            ],
        ),
    ]
