# Generated by Django 4.1.3 on 2022-12-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0024_transaction_is_entry_futurestrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurestrade',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='상태'),
        ),
    ]
