# Generated by Django 4.1.3 on 2022-12-12 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0028_remove_transaction_is_entry_futurestrade_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurestrade',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.futuresaccount', verbose_name='계좌'),
        ),
        migrations.AlterField(
            model_name='futurestrade',
            name='position',
            field=models.SmallIntegerField(choices=[(1, 'Long'), (-1, 'Short')], default=1, verbose_name='포지션'),
        ),
    ]
