# Generated by Django 4.1.3 on 2022-12-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0030_alter_futurestrade_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurestrade',
            name='position',
            field=models.SmallIntegerField(choices=[(1, 'Long'), (-1, 'Short')], verbose_name='포지션'),
        ),
    ]
