# Generated by Django 4.1.3 on 2022-12-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0031_alter_futurestrade_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurestrade',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='수수료'),
        ),
        migrations.AddField(
            model_name='futurestrade',
            name='paper_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='평가손익'),
        ),
        migrations.AddField(
            model_name='futurestrade',
            name='realized_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='실현손익'),
        ),
        migrations.AddField(
            model_name='futurestrade',
            name='risk',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='리스크'),
        ),
        migrations.AddField(
            model_name='futurestrade',
            name='stop_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='손절가'),
        ),
    ]
