# Generated by Django 4.1.3 on 2022-12-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0033_rename_entry_price_transaction_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurestrade',
            name='num_exit_cons',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='총청산계약수'),
        ),
    ]
