# Generated by Django 4.1.3 on 2022-12-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0034_alter_futurestrade_num_exit_cons'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturesRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='날짜')),
                ('principal', models.DecimalField(blank=True, decimal_places=0, max_digits=12, verbose_name='총시드(원)')),
                ('principal_krw', models.DecimalField(blank=True, decimal_places=0, max_digits=12, verbose_name='시드(원)')),
                ('principal_usd', models.DecimalField(blank=True, decimal_places=1, max_digits=12, verbose_name='시드(달러)')),
                ('value', models.DecimalField(blank=True, decimal_places=0, max_digits=12, verbose_name='총자산')),
                ('value_usd', models.DecimalField(blank=True, decimal_places=0, max_digits=12, verbose_name='자산(달러)')),
                ('commission', models.DecimalField(blank=True, decimal_places=0, max_digits=9, verbose_name='수수료')),
                ('gross_profit', models.DecimalField(blank=True, decimal_places=0, max_digits=12, verbose_name='누적수익')),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='num_cons',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='acc_from',
            field=models.CharField(choices=[('N', '없음'), ('C', '현금'), ('S', '주식'), ('F', '선물')], max_length=10, verbose_name='출금계좌'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='acc_to',
            field=models.CharField(choices=[('N', '없음'), ('C', '현금'), ('S', '주식'), ('F', '선물')], max_length=10, verbose_name='입금계좌'),
        ),
    ]
