# Generated by Django 4.1.3 on 2022-12-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0037_remove_futurestrade_account_futurestrade_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='태그')),
            ],
        ),
        migrations.RemoveField(
            model_name='futurestrade',
            name='description',
        ),
        migrations.AddField(
            model_name='futurestrade',
            name='entry_reason',
            field=models.TextField(blank=True, null=True, verbose_name='진입 이유'),
        ),
        migrations.AddField(
            model_name='futurestrade',
            name='exit_reason',
            field=models.TextField(blank=True, null=True, verbose_name='청산 이유'),
        ),
        migrations.AddField(
            model_name='futurestrade',
            name='mental',
            field=models.SmallIntegerField(blank=True, choices=[(-1, 'Bad'), (0, 'Normal'), (1, 'Good')], null=True, verbose_name='포지션'),
        ),
        migrations.AlterField(
            model_name='futurestrade',
            name='ebest_code',
            field=models.CharField(max_length=20, verbose_name='월물코드'),
        ),
        migrations.AddField(
            model_name='futurestrade',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='trades', to='trading.tags', verbose_name='태그'),
        ),
    ]
