# Generated by Django 4.1.3 on 2022-12-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0038_tags_remove_futurestrade_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurestrade',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='trades', to='trading.tags', verbose_name='태그'),
        ),
    ]
