# Generated by Django 4.1.3 on 2022-12-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0039_alter_futurestrade_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurestrade',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='보유기간'),
        ),
    ]
