# Generated by Django 4.1.3 on 2022-12-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0040_futurestrade_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurestrade',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='보유기간(시간)'),
        ),
        migrations.AlterField(
            model_name='futurestrade',
            name='mental',
            field=models.CharField(blank=True, choices=[('Bad', 'Bad'), ('Normal', 'Normal'), ('Good', 'Good')], max_length=10, null=True, verbose_name='멘탈'),
        ),
    ]
