# Generated by Django 4.1.3 on 2022-12-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0041_alter_futurestrade_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futurestrade',
            name='tags',
        ),
        migrations.AddField(
            model_name='futurestrade',
            name='entry_tags',
            field=models.ManyToManyField(blank=True, related_name='entry_trades', to='trading.tags', verbose_name='진입태그'),
        ),
        migrations.AddField(
            model_name='futurestrade',
            name='exit_tags',
            field=models.ManyToManyField(blank=True, related_name='exit_trades', to='trading.tags', verbose_name='청산태그'),
        ),
    ]
