# Generated by Django 4.1.3 on 2022-12-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0043_alter_tags_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('KRWUSD', models.DecimalField(decimal_places=5, max_digits=12)),
                ('KRWEUR', models.DecimalField(decimal_places=5, max_digits=12)),
                ('KRWCNY', models.DecimalField(decimal_places=5, max_digits=12)),
                ('KRWHKD', models.DecimalField(decimal_places=5, max_digits=12)),
                ('KRWJPY', models.DecimalField(decimal_places=5, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='FuturesStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='날짜')),
                ('principal', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='총시드(원)')),
                ('principal_krw', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='시드(원)')),
                ('principal_usd', models.DecimalField(decimal_places=1, max_digits=12, verbose_name='시드(달러)')),
                ('value', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='총자산(원)')),
                ('value_usd', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='달러자산')),
                ('commission', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='누적수수료')),
                ('realized_profit', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='누적실현손익')),
                ('paper_profit', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='평가손익')),
                ('averge_realized_profit', models.DecimalField(blank=True, decimal_places=0, max_digits=12, verbose_name='평균실현손익')),
                ('average_ptr', models.FloatField(verbose_name='평균손익비')),
                ('winning_rate', models.FloatField(verbose_name='승률')),
                ('cagr', models.FloatField(verbose_name='승률')),
            ],
        ),
        migrations.DeleteModel(
            name='FuturesRecord',
        ),
    ]
