# Generated by Django 4.1.3 on 2022-12-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0044_currencyrates_futuresstat_delete_futuresrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('symbol', models.CharField(max_length=20)),
                ('rate', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
            ],
        ),
    ]
