# Generated by Django 4.1.3 on 2022-12-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0045_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futuresinstrument',
            name='currency',
        ),
        migrations.AddField(
            model_name='futuresinstrument',
            name='currency2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trading.currency'),
        ),
    ]
