# Generated by Django 4.1.3 on 2022-12-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0046_remove_futuresinstrument_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futuresinstrument',
            old_name='currency2',
            new_name='currency',
        ),
    ]
