# Generated by Django 4.1.3 on 2022-12-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0048_futurestrade_commission_krw_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyRates',
        ),
        migrations.RemoveField(
            model_name='futurestrade',
            name='commission_krw',
        ),
        migrations.RemoveField(
            model_name='futurestrade',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='futurestrade',
            name='realized_profit_krw',
        ),
        migrations.RemoveField(
            model_name='futurestrade',
            name='risk',
        ),
        migrations.RemoveField(
            model_name='futurestrade',
            name='stop_price',
        ),
        migrations.AddField(
            model_name='futurestrade',
            name='timeframe',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='타임프레임'),
        ),
    ]
