# Generated by Django 4.1.3 on 2022-12-21 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0050_futuresaccount2_remove_futuresentry_account_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FuturesAccount2',
            new_name='FuturesAccount',
        ),
    ]
