# Generated by Django 4.1.3 on 2022-12-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0051_rename_futuresaccount2_futuresaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futuresaccount',
            old_name='pricnipal_usd',
            new_name='principal_usd',
        ),
    ]
