# Generated by Django 4.1.3 on 2022-12-21 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0054_remove_futuresaccount_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuresaccount',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='futures', to='trading.asset', verbose_name='자산종류'),
        ),
    ]
