# Generated by Django 4.1.3 on 2022-12-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0058_futurestrade_stop_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order_id',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='주문번호'),
        ),
    ]
