# Generated by Django 4.1.3 on 2022-12-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0059_transaction_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.PositiveSmallIntegerField(verbose_name='주문번호'),
        ),
        migrations.CreateModel(
            name='FuturesNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('memo', models.TextField(verbose_name='메모')),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='tags', to='trading.tags', verbose_name='태그')),
            ],
        ),
    ]
