# Generated by Django 4.1.3 on 2022-12-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0060_alter_transaction_order_id_futuresnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuresnote',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='futuresnote',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='trading.tags', verbose_name='태그'),
        ),
    ]
