# Generated by Django 4.1.3 on 2022-12-25 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0062_rename_futuresnote_note_noteimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteimage',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trading.note', verbose_name='image'),
        ),
    ]
