# Generated by Django 4.1.3 on 2022-12-25 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0063_alter_noteimage_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteimage',
            name='note',
        ),
        migrations.AlterField(
            model_name='noteimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trading/images'),
        ),
        migrations.CreateModel(
            name='NoteFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='trading/files')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='trading.note', verbose_name='파일')),
            ],
        ),
    ]
