# Generated by Django 4.1.3 on 2022-12-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0064_remove_noteimage_note_alter_noteimage_image_notefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notefile',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
