# Generated by Django 4.1.3 on 2022-12-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0065_notefile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notefile',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
