# Generated by Django 4.1.3 on 2022-12-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0066_alter_notefile_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FuturesStat',
        ),
        migrations.AlterField(
            model_name='futurestrade',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='수수료'),
        ),
    ]
