# Generated by Django 4.1.3 on 2022-12-27 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0067_delete_futuresstat_alter_futurestrade_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futurestrade',
            name='strategy',
        ),
        migrations.AddField(
            model_name='futuresstrategy',
            name='target',
            field=models.CharField(blank=True, choices=[('Volatility', '변동성흡수'), ('Direction', '방향성')], max_length=50, null=True, verbose_name='수익대상'),
        ),
        migrations.AddField(
            model_name='futuresstrategy',
            name='type',
            field=models.CharField(choices=[('Entry', '진입'), ('Exit', '청산')], default='Entry', max_length=10, verbose_name='진입/청산'),
        ),
        migrations.AddField(
            model_name='futurestrade',
            name='entry_strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entry_trades', to='trading.futuresstrategy', verbose_name='진입전략'),
        ),
        migrations.AddField(
            model_name='futurestrade',
            name='exit_strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exit_trades', to='trading.futuresstrategy', verbose_name='청산전략'),
        ),
    ]
