# Generated by Django 4.1.3 on 2023-01-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0068_remove_futurestrade_strategy_futuresstrategy_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurestrade',
            name='realized_profit_ticks',
            field=models.PositiveIntegerField(default=0, verbose_name='실현손익(틱)'),
        ),
        migrations.AlterField(
            model_name='futuresstrategy',
            name='type',
            field=models.CharField(choices=[('entry', '진입'), ('exit', '청산')], default='Entry', max_length=10, verbose_name='진입/청산'),
        ),
    ]
