# Generated by Django 4.1.3 on 2023-01-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0069_futurestrade_realized_profit_ticks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurestrade',
            name='realized_profit_ticks',
            field=models.FloatField(default=0, verbose_name='실현손익(틱)'),
        ),
    ]
