# Generated by Django 4.1.3 on 2023-03-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0071_futuresinstrument_is_micro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Futures', 'Futures'), ('Option', 'Option'), ('Spread', 'Spread')], default='Futures', max_length=20, verbose_name='타입'),
        ),
    ]
