# Generated by Django 4.1.3 on 2023-03-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0072_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuresinstrument',
            name='option_weight',
            field=models.SmallIntegerField(default=50, verbose_name='옵션승수'),
        ),
        migrations.AddField(
            model_name='futurestrade',
            name='type',
            field=models.CharField(choices=[('Futures', 'Futures'), ('Option', 'Option'), ('Spread', 'Spread')], default='Futures', max_length=20, verbose_name='타입'),
        ),
    ]
