# Generated by Django 4.1.3 on 2023-03-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0073_futuresinstrument_option_weight_futurestrade_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuresinstrument',
            name='option_unit',
            field=models.SmallIntegerField(default=1, verbose_name='옵션단위'),
        ),
    ]
