# Generated by Django 4.1.3 on 2023-06-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0075_futuresinstrument_option_prefixes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futuresinstrument',
            old_name='option_prefixes',
            new_name='option_codes',
        ),
    ]
