# Generated by Django 4.1.3 on 2023-06-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0076_rename_option_prefixes_futuresinstrument_option_codes'),
    ]

    operations = [
        
    ]
