# Generated by Django 4.1.3 on 2024-11-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0077_remove_futuresinstrument_option_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='futuresinstrument',
            name='option_codes',
            field=models.CharField(default='', max_length=200, verbose_name='옵션명'),
        ),
    ]
