# Generated by Django 4.1.3 on 2025-04-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0079_remove_futuresinstrument_option_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futuresinstrument',
            name='option_unit',
        ),
        migrations.RemoveField(
            model_name='futuresinstrument',
            name='option_weight',
        ),
        migrations.AlterField(
            model_name='futuresinstrument',
            name='option_codes',
            field=models.CharField(max_length=200, verbose_name='옵션명'),
        ),
    ]
