# Generated by Django 4.1.3 on 2025-04-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0080_remove_futuresinstrument_option_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuresinstrument',
            name='option_codes',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='옵션명'),
        ),
    ]
