# Generated by Django 4.1.3 on 2025-04-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0082_alter_futuresinstrument_option_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuresinstrument',
            name='option_codes',
            field=models.CharField(default='', max_length=200, verbose_name='옵션코드'),
        ),
    ]
