# Generated by Django 4.1.3 on 2025-04-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0084_alter_futuresinstrument_option_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.CharField(default='A001', max_length=100, verbose_name='계좌번호'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='device',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='접속기기'),
        ),
    ]
