# Generated by Django 5.2.4 on 2025-12-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0086_futurestrade_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', '일간'), ('weekly', '주간'), ('monthly', '월간')], default='weekly', max_length=20, verbose_name='기간')),
                ('profit_goal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='수익 목표')),
                ('max_loss_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='최대 손실 한도')),
                ('max_trades_per_day', models.PositiveIntegerField(default=5, verbose_name='일일 최대 거래 횟수')),
                ('alert_consecutive_losses', models.PositiveIntegerField(default=3, verbose_name='연속 손실 알림 횟수')),
                ('alert_low_win_rate', models.DecimalField(decimal_places=2, default=40, max_digits=5, verbose_name='낮은 승률 알림 기준 (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
