# Generated by Django 2.1.4 on 2018-12-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file_location',
            field=models.FileField(unique=True, upload_to='maths/books/'),
        ),
    ]
