# Generated by Django 2.1.4 on 2018-12-28 17:47

from django.db import migrations, models
import maths.models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0003_auto_20181228_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file_location',
            field=models.FileField(unique=True, upload_to=maths.models.set_book_name),
        ),
    ]
