# Generated by Django 2.1.4 on 2018-12-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0003_auto_20181231_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('Test', 'Test'), ('Worksheet', 'Worksheet'), ('Lecture Note', 'Lecture Note'), ('Quiz', 'Quiz'), ('Book', 'Book')], max_length=16),
        ),
    ]
