# Generated by Django 2.1.4 on 2018-12-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0004_auto_20181228_1747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Document',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='file_location',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='file_location',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='key_location',
            new_name='key',
        ),
    ]
