# Generated by Django 2.1.4 on 2018-12-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0004_auto_20181231_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(choices=[('IBHL', 'IB HighLevel'), ('IBSL', 'IB Standard'), ('APAB', 'AP Calculus AB'), ('APBC', 'AP Calculus BC'), ('PreCal', 'Pre Calculus'), ('Algebra2', 'Algebra 2'), ('Geometry', 'Geometry'), ('Y9', 'Year 9'), ('Y10', 'Year 10'), ('Y11', 'Year 11'), ('etc', 'etc')], max_length=16),
        ),
        migrations.AlterField(
            model_name='document',
            name='course',
            field=models.CharField(choices=[('IBHL', 'IB HighLevel'), ('IBSL', 'IB Standard'), ('APAB', 'AP Calculus AB'), ('APBC', 'AP Calculus BC'), ('PreCal', 'Pre Calculus'), ('Algebra2', 'Algebra 2'), ('Geometry', 'Geometry'), ('Y9', 'Year 9'), ('Y10', 'Year 10'), ('Y11', 'Year 11'), ('etc', 'etc')], max_length=16),
        ),
        migrations.AlterField(
            model_name='pastexampaper',
            name='course',
            field=models.CharField(choices=[('IBHL', 'IB HighLevel'), ('IBSL', 'IB Standard'), ('APAB', 'AP Calculus AB'), ('APBC', 'AP Calculus BC'), ('PreCal', 'Pre Calculus'), ('Algebra2', 'Algebra 2'), ('Geometry', 'Geometry'), ('Y9', 'Year 9'), ('Y10', 'Year 10'), ('Y11', 'Year 11'), ('etc', 'etc')], max_length=16),
        ),
    ]
