# Generated by Django 2.1.4 on 2018-12-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0007_auto_20181231_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('course', models.ManyToManyField(blank=True, to='maths.Course')),
                ('lecture_note', models.ManyToManyField(blank=True, related_name='lecture_note', to='maths.Document')),
                ('worksheet', models.ManyToManyField(blank=True, related_name='worksheet', to='maths.Document')),
            ],
        ),
    ]
