# Generated by Django 2.1.4 on 2018-12-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0008_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='lecture',
            field=models.ManyToManyField(blank=True, to='maths.Lecture'),
        ),
    ]
