# Generated by Django 2.1.4 on 2018-12-31 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0009_auto_20181231_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='title',
            new_name='name',
        ),
    ]
