# Generated by Django 2.1.4 on 2019-01-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0013_auto_20190102_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
