# Generated by Django 2.1.4 on 2019-01-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0014_document_reputation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('Test', 'Test'), ('Worksheet', 'Worksheet'), ('Note', 'Note'), ('Quiz', 'Quiz'), ('Book', 'Book')], max_length=16),
        ),
    ]
