# Generated by Django 2.1.4 on 2019-01-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0015_auto_20190103_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.CharField(choices=[('IBHL', 'IB HighLevel'), ('IBSL', 'IB Standard'), ('APAB', 'AP Calculus AB'), ('APBC', 'AP Calculus BC'), ('PreCal', 'Pre Calculus'), ('Algebra2', 'Algebra 2'), ('Geometry', 'Geometry'), ('Y9', 'Year 9'), ('Y10', 'Year 10'), ('Y11', 'Year 11'), ('etc', 'etc')], default='Algebra2', max_length=16),
        ),
        migrations.AlterField(
            model_name='klass',
            name='lecture',
            field=models.ManyToManyField(blank=True, to='maths.Lecture'),
        ),
    ]
