# Generated by Django 2.1.4 on 2019-01-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0016_auto_20190105_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='course',
            field=models.CharField(choices=[('IBHL', 'IB HighLevel'), ('IBSL', 'IB Standard'), ('APAB', 'AP Calculus AB'), ('APBC', 'AP Calculus BC'), ('PreCal', 'Pre Calculus'), ('Algebra2', 'Algebra 2'), ('Geometry', 'Geometry'), ('Y9', 'Year 9'), ('Y10', 'Year 10'), ('Y11', 'Year 11'), ('etc', 'etc')], max_length=16),
        ),
    ]
