# Generated by Django 2.1.4 on 2019-01-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0018_auto_20190106_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastexampaper',
            name='exam',
            field=models.CharField(choices=[('IB STANDARD', 'IBSL'), ('IB HIGHLEVEL', 'IBHL'), ('AP Calculus AB', 'APAB'), ('AP Calculus BC', 'APBC'), ('AP Statistics', 'AP STAT'), ('SAT Math', 'SAT'), ('SAT2 Math', 'SAT2')], max_length=32),
        ),
        migrations.AlterField(
            model_name='pastexampaper',
            name='pub_year',
            field=models.IntegerField(),
        ),
    ]
