# Generated by Django 2.1.4 on 2019-01-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0019_auto_20190106_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastexampaper',
            name='pub_year',
            field=models.DateField(),
        ),
    ]
