# Generated by Django 2.1.4 on 2019-01-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0020_auto_20190106_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastexampaper',
            name='exam',
            field=models.CharField(blank=True, choices=[('IB Standard', 'IBSL'), ('IB Highlevel', 'IBHL'), ('AP Calculus AB', 'APAB'), ('AP Calculus BC', 'APBC'), ('AP Statistics', 'AP STAT'), ('SAT Math', 'SAT'), ('SAT2 Math', 'SAT2')], max_length=32),
        ),
    ]
