# Generated by Django 2.1.4 on 2019-01-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0021_auto_20190106_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('Test', 'Test'), ('Worksheet', 'Worksheet'), ('Note', 'Note'), ('Quiz', 'Quiz'), ('Book', 'Book'), ('Exam', 'Exam')], max_length=16),
        ),
        migrations.AlterField(
            model_name='pastexampaper',
            name='exam',
            field=models.CharField(choices=[('IB Standard', 'IBSL'), ('IB Highlevel', 'IBHL'), ('AP Calculus AB', 'APAB'), ('AP Calculus BC', 'APBC'), ('AP Statistics', 'AP STAT'), ('SAT Math', 'SAT'), ('SAT2 Math', 'SAT2')], max_length=32),
        ),
        migrations.AlterField(
            model_name='pastexampaper',
            name='paper',
            field=models.ManyToManyField(blank=True, to='maths.Document'),
        ),
    ]
