# Generated by Django 2.1.4 on 2019-01-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0022_auto_20190106_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastexampaper',
            name='exam',
            field=models.CharField(choices=[('IB Standard', 'IBSL'), ('IB Highlevel', 'IBHL'), ('AP Calculus AB', 'APAB'), ('AP Calculus BC', 'APBC'), ('AP Statistics', 'AP STAT'), ('A-Level Maths', 'A-Level'), ('SAT Math', 'SAT'), ('SAT2 Math', 'SAT2')], max_length=32),
        ),
    ]
