# Generated by Django 2.1.4 on 2019-01-10 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0023_auto_20190111_0059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastexampaper',
            options={'ordering': ['exam', '-pub_year']},
        ),
    ]
