# Generated by Django 2.1.4 on 2019-01-10 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0024_auto_20190111_0107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastexampaper',
            options={},
        ),
        migrations.RemoveField(
            model_name='klass',
            name='lecture',
        ),
        migrations.AddField(
            model_name='lecture',
            name='klass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maths.Klass'),
        ),
    ]
