# Generated by Django 2.1.4 on 2019-01-10 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0025_auto_20190111_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maths.Klass'),
        ),
    ]
