# Generated by Django 2.1.4 on 2019-01-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0026_auto_20190111_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='course',
        ),
    ]
