# Generated by Django 2.1.4 on 2019-01-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0027_remove_lecture_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='unit',
            field=models.IntegerField(default=0),
        ),
    ]
