# Generated by Django 5.2.4 on 2025-11-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echomind', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lapse_category',
            name='level',
            field=models.CharField(choices=[('passive lapse', 'Passive Lapse'), ('narrative drift', 'Narrative Drift'), ('cognitive drift', 'Cognitive Drift'), ('affective lapse', 'Affective lapse')], default='passive lapse', max_length=20),
        ),
    ]
