# Generated by Django 5.2.4 on 2025-11-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echomind', '0002_alter_lapse_category_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lapse_category',
            name='level',
        ),
        migrations.AddField(
            model_name='attentional_lapse',
            name='lapse_type',
            field=models.CharField(choices=[('passive lapse', 'Passive Lapse'), ('narrative drift', 'Narrative Drift'), ('intentional lapse', 'Intentional Lapse'), ('affective lapse', 'Affective Lapse')], default='passive lapse', max_length=20),
        ),
    ]
