# Generated by Django 5.2.4 on 2025-11-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echomind', '0003_remove_lapse_category_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='status_tags',
            field=models.ManyToManyField(blank=True, related_name='activities', to='echomind.status_tag'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_tags',
            field=models.ManyToManyField(blank=True, related_name='activities', to='echomind.activity_tag'),
        ),
    ]
