# Generated by Django 5.2.4 on 2025-11-05 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echomind', '0004_activity_tag_alter_activity_status_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_tag',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='echomind.activity_category'),
        ),
    ]
