# Generated by Django 5.2.4 on 2025-11-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echomind', '0005_activity_tag_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lapse_category',
            options={'ordering': ['lapse_type', 'name']},
        ),
        migrations.AddField(
            model_name='lapse_category',
            name='lapse_type',
            field=models.CharField(choices=[('passive lapse', 'Passive Lapse'), ('narrative drift', 'Narrative Drift'), ('intentional lapse', 'Intentional Lapse'), ('affective lapse', 'Affective Lapse')], default='passive lapse', max_length=20),
        ),
        migrations.AlterField(
            model_name='lapse_category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
