# Generated by Django 5.2.4 on 2025-11-09 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echomind', '0006_alter_lapse_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Estimated time in hours', max_digits=4, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echomind.activity_category')),
            ],
            options={
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='planned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='echomind.plan'),
        ),
    ]
