# Generated by Django 5.2.4 on 2025-11-06 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echomind', '0006_alter_lapse_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('estimated_hours', models.DecimalField(decimal_places=1, help_text='Estimated time in hours', max_digits=4)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echomind.activity_category')),
            ],
            options={
                'ordering': ['-date', 'category'],
            },
        ),
    ]
