# Generated by Django 5.2.4 on 2025-11-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echomind', '0007_plan_activity_planned_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_category',
            name='color',
            field=models.CharField(default='#667eea,#764ba2', help_text='Gradient colors separated by comma (e.g., #667eea,#764ba2)', max_length=50),
        ),
    ]
