# Generated by Django 5.2.4 on 2025-11-09 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echomind', '0008_activity_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attentional_lapse',
            name='lapse_type',
            field=models.CharField(choices=[('passive lapse', 'Passive Lapse'), ('intentional lapse', 'Intentional Lapse')], default='passive lapse', max_length=20),
        ),
        migrations.AlterField(
            model_name='lapse_category',
            name='lapse_type',
            field=models.CharField(choices=[('passive lapse', 'Passive Lapse'), ('intentional lapse', 'Intentional Lapse')], default='passive lapse', max_length=20),
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='echomind.activity_category')),
            ],
            options={
                'ordering': ['is_completed', '-created_at'],
            },
        ),
    ]
