# Generated by Django 5.2.4 on 2025-11-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echomind', '0009_alter_attentional_lapse_lapse_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='activity_tags',
            field=models.ManyToManyField(blank=True, related_name='plans', to='echomind.activity_tag'),
        ),
    ]
