# Generated by Django 2.2.6 on 2019-11-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('krw', models.IntegerField(blank=True, null=True)),
                ('cny', models.IntegerField(blank=True, null=True)),
                ('usd', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cash',
            },
        ),
        migrations.CreateModel(
            name='Futures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('futures_in_krw', models.IntegerField(blank=True, null=True)),
                ('futures_in_usd', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Derivative',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stocks', models.IntegerField(blank=True, null=True)),
                ('etfs', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Equities',
            },
        ),
    ]
