# Generated by Django 2.1.4 on 2019-01-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cny',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='krw',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usd',
            name='date',
            field=models.DateField(),
        ),
    ]
