# Generated by Django 2.1.4 on 2019-01-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20190106_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('krw', models.IntegerField()),
                ('cny', models.IntegerField()),
                ('usd', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
