# Generated by Django 2.1.4 on 2019-01-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_cash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CNY',
        ),
        migrations.DeleteModel(
            name='KRW',
        ),
        migrations.DeleteModel(
            name='USD',
        ),
        migrations.AlterField(
            model_name='cash',
            name='cny',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cash',
            name='krw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cash',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cash',
            name='usd',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
