# Generated by Django 2.2.6 on 2019-10-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20190107_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Futures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('futures_in_krw', models.IntegerField(blank=True, null=True)),
                ('futures_in_usd', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stocks', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
