# Generated by Django 2.2.6 on 2019-10-06 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_futures_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='futures',
            options={'verbose_name': 'Future'},
        ),
    ]
