# Generated by Django 2.2.6 on 2019-10-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20191007_0317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='futures',
            options={'verbose_name': 'Derivative'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Equity'},
        ),
        migrations.AddField(
            model_name='stock',
            name='etfs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
