# Generated by Django 2.2.6 on 2019-10-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20191007_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cash',
            options={'verbose_name_plural': 'Cash'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name_plural': 'Equities'},
        ),
    ]
