# Generated by Django 3.0.3 on 2020-09-30 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0002_auto_20200929_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework', models.BooleanField(verbose_name='숙제')),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField(verbose_name='시작시간')),
                ('enddate', models.DateTimeField(verbose_name='마친시간')),
                ('name', models.CharField(max_length=64, verbose_name='수업내용')),
                ('note', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='is_group',
            field=models.BooleanField(default=True, verbose_name='그룹수업여부'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(help_text='수요일 3시-4시30분 일요일 4시-5시30분의 경우                   WED15001630;SUN16001730', max_length=250, verbose_name='수업시간'),
        ),
        migrations.DeleteModel(
            name='CourseDetail',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tutoring.Course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='students',
            field=models.ManyToManyField(to='tutoring.Student', verbose_name='출석학생'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tutoring.Lesson'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tutoring.Student'),
        ),
    ]
