# Generated by Django 3.0.3 on 2020-09-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0003_auto_20200930_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='tutoring.Student', verbose_name='등록학생'),
        ),
    ]
