# Generated by Django 3.0.3 on 2020-09-30 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0004_course_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('-date',)},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='startdate',
        ),
        migrations.AddField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=datetime.date(2020, 9, 30), verbose_name='날짜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='end',
            field=models.TimeField(default=datetime.time(23, 17, 23, 897437), verbose_name='마친시간'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='start',
            field=models.TimeField(default=datetime.time(23, 17, 30, 317690), verbose_name='시작시간'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='tutoring.Student', verbose_name='학생'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='tution_group',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='수업료(그룹)'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='tution_private',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='수업료(개인)'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='deposit',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
