# Generated by Django 3.0.3 on 2020-10-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0006_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_group',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='tution_group',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='tution_private',
        ),
        migrations.AddField(
            model_name='course',
            name='tution',
            field=models.DecimalField(decimal_places=2, default=400, max_digits=8, verbose_name='수업료'),
            preserve_default=False,
        ),
    ]
