# Generated by Django 3.0.3 on 2020-10-02 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0007_auto_20201001_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-startdate',)},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('pk',)},
        ),
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.date(2020, 10, 2), verbose_name='등록일'),
            preserve_default=False,
        ),
    ]
