# Generated by Django 3.0.3 on 2020-10-03 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0008_auto_20201002_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='students',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='tution',
            new_name='tuition',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='students',
            new_name='student',
        ),
    ]
