# Generated by Django 3.0.3 on 2020-10-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0009_auto_20201003_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='student',
        ),
        migrations.RemoveField(
            model_name='tuition',
            name='note',
        ),
        migrations.AddField(
            model_name='tuition',
            name='payment',
            field=models.CharField(choices=[('위챗페이', 'wechat'), ('알리페이', 'alipay'), ('현금', 'cash')], default='wechat', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendence',
            name='homework',
            field=models.SmallIntegerField(choices=[('잘해옴', 1), ('부족', 2), ('안함', 3)], verbose_name='숙제'),
        ),
    ]
