# Generated by Django 3.0.3 on 2020-10-05 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0013_student_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendence',
            unique_together={('lesson', 'student')},
        ),
    ]
