# Generated by Django 3.0.3 on 2020-10-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0014_auto_20201005_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='단원'),
        ),
    ]
