# Generated by Django 3.0.3 on 2020-10-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0015_lesson_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='textbook',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='주교재'),
        ),
    ]
