# Generated by Django 3.0.3 on 2020-10-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0017_auto_20201012_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='homework',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
