# Generated by Django 3.0.3 on 2020-10-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0018_auto_20201013_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='homework',
            field=models.CharField(blank=True, choices=[(1, '잘해옴'), (2, '부족'), (3, '안함')], max_length=250, null=True),
        ),
    ]
