# Generated by Django 3.0.3 on 2020-10-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0020_auto_20201013_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='homework',
            field=models.CharField(blank=True, choices=[(1, '잘해옴'), (2, '부족'), (3, '안함'), (4, '')], max_length=250, null=True),
        ),
    ]
