# Generated by Django 3.0.3 on 2020-10-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0021_auto_20201013_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('-date', '-start')},
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=90, verbose_name='진행시간(분)'),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='homework',
            field=models.CharField(blank=True, choices=[('1', '잘해옴'), ('2', '부족'), ('3', '안함'), ('4', '')], max_length=250, null=True),
        ),
    ]
