# Generated by Django 3.0.3 on 2020-11-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0022_auto_20201019_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='tuition',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='수업료'),
        ),
    ]
