# Generated by Django 4.1.1 on 2022-09-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0023_lesson_tuition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='tuition',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='수업료'),
        ),
    ]
