# Generated by Django 4.1.1 on 2022-09-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0024_alter_lesson_tuition'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pay_remain',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='student',
            name='pay_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
