# Generated by Django 4.1.3 on 2023-12-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0026_remove_student_pay_remain_remove_student_pay_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(-1, '지출'), (1, '수입')])),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('-status', '-date')},
        ),
    ]
