# Generated by Django 4.1.3 on 2023-12-14 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0027_financialcategory_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialcategory',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(2, '지출'), (1, '수입')]),
        ),
        migrations.CreateModel(
            name='FinancialItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('note', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tutoring.financialcategory')),
            ],
        ),
    ]
