# Generated by Django 4.1.3 on 2024-01-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0030_consult'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('memo', models.TextField()),
            ],
        ),
    ]
