# Generated by Django 4.1.3 on 2024-01-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0031_dailymemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymemo',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
