# Generated by Django 4.1.3 on 2024-02-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0032_dailymemo_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year2',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '등록'), (2, '졸업'), (3, '퇴원'), (4, '미등록')]),
        ),
    ]
