# Generated by Django 4.1.3 on 2024-03-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0033_student_year2_alter_student_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('status', '-date')},
        ),
        migrations.AddField(
            model_name='curriculum',
            name='level',
            field=models.SmallIntegerField(blank=True, choices=[(1, '중등'), (2, '고등'), (3, 'AP/IB'), (4, '경시')], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(choices=[('SASPX', 'SASPX'), ('SASPD', 'SASPD'), ('BISSPD', 'BISSPD'), ('BISSPX', 'BISSPX'), ('SHID', 'SHID'), ('SCIS', 'SCIS'), ('YCIS', 'YCIS'), ('SSIS', 'SSIS'), ('한국학교', '한국학교'), ('페이스톤', '페이스톤')], max_length=64),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '등록'), (2, '퇴원'), (3, '졸업'), (4, '미등록')]),
        ),
    ]
