# Generated by Django 4.1.3 on 2024-03-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0036_tuitionnotice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuitionnotice',
            name='curriculum',
        ),
        migrations.AddField(
            model_name='tuitionnotice',
            name='course',
            field=models.ManyToManyField(to='tutoring.course', verbose_name='과정'),
        ),
    ]
