# Generated by Django 4.1.3 on 2024-03-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0037_remove_tuitionnotice_curriculum_tuitionnotice_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionnotice',
            name='notice_last_tution_date',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tuitionnotice',
            name='notice_next_tuition',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
