# Generated by Django 4.1.3 on 2024-03-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0038_tuitionnotice_notice_last_tution_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuitionnotice',
            old_name='notice_last_tution_date',
            new_name='notice_last_tuition_date',
        ),
    ]
