# Generated by Django 4.1.3 on 2024-03-12 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0040_tuitionnotice_tuition_alter_tuitionnotice_attendence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuitionnotice',
            name='last_payment_date',
        ),
    ]
