# Generated by Django 4.1.3 on 2024-03-13 10:33

from django.db import migrations, models
import django.db.models.deletion
import tutoring.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0041_remove_tuitionnotice_last_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionnotice',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=tutoring.models.TuitionNotice.set_file_name),
        ),
        migrations.AlterField(
            model_name='tuitionnotice',
            name='tuition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice', to='tutoring.tuition'),
        ),
    ]
