# Generated by Django 4.1.3 on 2024-03-17 14:55

from django.db import migrations, models
import tutoring.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0042_tuitionnotice_pdf_alter_tuitionnotice_tuition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=tutoring.models.Homework.set_file_name)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='hwfile',
            field=models.ManyToManyField(blank=True, null=True, to='tutoring.homework', verbose_name='숙제파일'),
        ),
    ]
