# Generated by Django 4.1.3 on 2024-03-26 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0044_alter_lesson_hwfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='hwfile',
            field=models.ManyToManyField(related_name='lesson', to='tutoring.homework', verbose_name='숙제파일'),
        ),
        migrations.CreateModel(
            name='ExtraLessonPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('start', models.TimeField(verbose_name='시작시간')),
                ('end', models.TimeField(verbose_name='종료시간')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tutoring.course')),
            ],
        ),
    ]
