# Generated by Django 4.1.3 on 2024-03-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0045_alter_lesson_hwfile_extralessonplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='extralessonplan',
            name='type',
            field=models.CharField(choices=[('add', '새수업추가'), ('remove', '기존수업삭제')], default='add', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extralessonplan',
            name='end',
            field=models.TimeField(blank=True, null=True, verbose_name='종료시간'),
        ),
        migrations.AlterField(
            model_name='extralessonplan',
            name='start',
            field=models.TimeField(blank=True, null=True, verbose_name='시작시간'),
        ),
    ]
