# Generated by Django 4.1.3 on 2024-04-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0047_alter_financialitem_options_attendence_attended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='attended',
            field=models.BooleanField(),
        ),
    ]
