# Generated by Django 4.1.3 on 2024-04-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0048_alter_attendence_attended'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendence',
            options={'ordering': ('-student__date',)},
        ),
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, to='tutoring.student', verbose_name='학생'),
        ),
    ]
