# Generated by Django 4.1.3 on 2024-04-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0049_alter_attendence_options_alter_course_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
