# Generated by Django 4.1.3 on 2024-04-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0050_course_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(to='tutoring.student', verbose_name='학생'),
        ),
    ]
