# Generated by Django 4.1.3 on 2024-04-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0051_alter_course_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='tuition',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='수업료'),
            preserve_default=False,
        ),
    ]
