# Generated by Django 4.1.3 on 2024-04-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0052_attendence_tuition'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='payment',
            field=models.CharField(choices=[('위챗페이', '위챗페이'), ('즈푸바오', '즈푸바오'), ('현금', '현금'), ('환불', '환불')], max_length=250),
        ),
    ]
