# Generated by Django 5.2.4 on 2025-12-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_advisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='app_type',
            field=models.CharField(choices=[('trading', 'Trading Advisor'), ('echomind', 'Echomind Advisor')], db_index=True, default='trading', max_length=20),
        ),
    ]
