# Generated by Django 5.2.4 on 2025-12-17 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_advisor', '0002_conversation_app_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='history_summary',
            field=models.TextField(blank=True, help_text='30일 이상 된 메시지들의 요약본'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='summary_generated_at',
            field=models.DateTimeField(blank=True, help_text='요약이 마지막으로 생성된 시점', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='60일 이상 된 메시지는 아카이빙됨'),
        ),
        migrations.CreateModel(
            name='ConversationMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='기억할 내용')),
                ('category', models.CharField(choices=[('strategy', '거래 전략'), ('rule', '거래 규칙'), ('lesson', '배운 교훈'), ('psychology', '심리/감정 관리'), ('risk', '리스크 관리'), ('pattern', '발견한 패턴'), ('goal', '목표/제약사항'), ('other', '기타')], default='other', max_length=20)),
                ('importance', models.IntegerField(default=5, help_text='중요도 (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='비활성화된 메모리는 AI에게 제공되지 않음')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='ai_advisor.conversation')),
                ('source_message', models.ForeignKey(blank=True, help_text='이 메모리가 추출된 원본 메시지', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_advisor.message')),
            ],
            options={
                'verbose_name': '대화 메모리',
                'verbose_name_plural': '대화 메모리들',
                'ordering': ['-importance', '-created_at'],
            },
        ),
    ]
