# Generated by Django 5.2.4 on 2025-12-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_advisor', '0003_conversation_history_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
