# Generated by Django 5.2.4 on 2025-12-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_advisor', '0004_message_input_tokens_message_output_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_long_term_memory', models.BooleanField(default=True, help_text='대화에서 중요한 사실을 자동으로 기억합니다', verbose_name='장기 기억 활성화')),
                ('message_retention_days', models.IntegerField(default=30, help_text='이 기간 내의 메시지만 전체 로드합니다 (나머지는 요약)', verbose_name='최근 메시지 보관 일수')),
                ('ai_model', models.CharField(choices=[('claude-sonnet-4-5', 'Claude Sonnet 4.5 (고품질, 느림)'), ('claude-haiku-4-5-20251001', 'Claude Haiku 4.5 (빠름, 저렴)')], default='claude-sonnet-4-5', max_length=50, verbose_name='AI 모델')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI 설정',
                'verbose_name_plural': 'AI 설정',
            },
        ),
    ]
