# Generated by Django 5.2.4 on 2025-12-18 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_advisor', '0004_fix_charset_utf8mb4'),
        ('ai_advisor', '0005_aisettings'),
    ]

    operations = [
    ]
