# Generated by Django 5.2.4 on 2025-12-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_advisor', '0006_merge_0004_fix_charset_utf8mb4_0005_aisettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='ai_model',
            field=models.CharField(choices=[('claude-sonnet-4-5', 'Claude Sonnet 4.5 (고품질, 느림)'), ('claude-haiku-4-5', 'Claude Haiku 4.5 (빠름, 저렴)')], default='claude-sonnet-4-5', max_length=50, verbose_name='AI 모델'),
        ),
    ]
