# Generated by Django 3.0.3 on 2020-09-17 17:12

import aops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=aops.models.set_file_name),
        ),
    ]
